### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by stanleyxu2005** [jmmills/docker-trac#1]
Great image! Maybe you can add a readme:
1. To point out where the docker image can be pulled. `docker pull jmills/trac`. 
2. Tell user how to persist git repository data to an external storage, like `-v /path/to/storage:/path/to/repo`.

**Comment by jmmills** [comment]
@stanleyxu2005 Thanks. I'll work on it, this was a very early on docker build for me, so sorry for the documentation being omitted.
